# Generated by Django 4.1.7 on 2023-03-31 09:23

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_favorite_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_request',
        ),
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('intend_time', models.DateTimeField(default=datetime.datetime(2023, 3, 31, 10, 23, 55, 943698, tzinfo=datetime.timezone.utc))),
                ('special_request', models.TextField(blank=True, default=None, null=True)),
                ('total_bill', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.customer')),
                ('list_product', models.ManyToManyField(through='product.Order', to='product.product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table', to='product.table')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=models.ForeignKey(db_column='order_table', on_delete=django.db.models.deletion.CASCADE, to='product.ordertable'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ordertable'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
