# Generated by Django 4.1.7 on 2023-04-05 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_special_request_order_special_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 5, 3, 15, 12, 69957, tzinfo=datetime.timezone.utc)),
        ),
    ]
