# Generated by Django 4.1.7 on 2023-04-07 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_comment_helpful_comment_not_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 11, 33, 52, 892957, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table', to='product.typetable'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
