# Generated by Django 4.1.7 on 2023-04-08 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_ordertable_intend_time_alter_ordertable_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 3, 39, 28, 128637, tzinfo=datetime.timezone.utc)),
        ),
    ]
