# Generated by Django 4.1.7 on 2023-04-08 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_ordertable_is_pending_alter_ordertable_intend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 15, 49, 37, 439442)),
        ),
    ]
