# Generated by Django 4.1.7 on 2023-04-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_ordertable_intend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_send_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 53, 39, 733555)),
        ),
    ]
