# Generated by Django 4.1.7 on 2023-04-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_customer_is_send_mail_alter_ordertable_intend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 56, 10, 767427)),
        ),
    ]
