# Generated by Django 4.1.7 on 2023-04-09 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_ordertable_is_payment_alter_ordertable_intend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 11, 2, 33, 950516)),
        ),
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sold', to='product.product')),
            ],
            options={
                'db_table': 'product_sold',
            },
        ),
    ]
