# Generated by Django 4.1.7 on 2023-04-09 18:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_alter_ordertable_intend_time_productsold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.IntegerField(unique=True)),
                ('start_money', models.DecimalField(decimal_places=3, max_digits=15)),
                ('end_money', models.DecimalField(decimal_places=3, max_digits=15)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type_customer',
            },
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 19, 43, 28, 952842)),
        ),
        migrations.CreateModel(
            name='DiscountBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sell_off', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('times', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 4, 9, 19, 43, 28, 952842))),
                ('status', models.BooleanField(default=True)),
                ('type_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecustomer', to='product.typecustomer')),
            ],
            options={
                'db_table': 'discount_bill',
            },
        ),
        migrations.CreateModel(
            name='RankCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.typecustomer')),
            ],
            options={
                'db_table': 'rank_customer',
                'unique_together': {('customer', 'type_customer')},
            },
        ),
    ]
