# Generated by Django 4.1.7 on 2023-04-09 23:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_typecustomer_alter_ordertable_intend_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='is_payment',
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 0, 33, 33, 401399)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 0, 33, 33, 402400)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ordertable'),
        ),
    ]
