# Generated by Django 4.1.7 on 2023-04-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_discountbill_times_customer_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 16, 8, 52, 501090)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 16, 8, 52, 501249)),
        ),
    ]
