# Generated by Django 4.1.7 on 2023-04-13 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_payment_must_pay_payment_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountbill',
            name='type_customer',
        ),
        migrations.AddField(
            model_name='discountbill',
            name='end_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discountbill',
            name='start_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 27, 20, 168217)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 1, 27, 20, 169723)),
        ),
    ]
