# Generated by Django 4.1.7 on 2023-04-14 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_discountbill_type_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 11, 2, 29, 60144)),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='start_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 11, 2, 29, 61143)),
        ),
        migrations.CreateModel(
            name='Comment_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_comment', models.ManyToManyField(blank=True, related_name='can_comment', to='product.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('is_comment', models.ManyToManyField(blank=True, related_name='is_comment', to='product.product')),
            ],
            options={
                'db_table': 'user_comment',
            },
        ),
    ]
