# Generated by Django 4.1.7 on 2023-04-14 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_discountbill_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_product',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 11, 56, 45, 101443)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 11, 56, 45, 102442)),
        ),
    ]
