# Generated by Django 4.1.7 on 2023-04-14 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_comment_product_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_product',
            name='can_comment',
        ),
        migrations.AlterField(
            model_name='comment_product',
            name='is_comment',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 12, 0, 49, 994345)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 12, 0, 49, 995346)),
        ),
    ]
