# Generated by Django 4.1.7 on 2023-04-14 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_discountbill_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_product',
            name='food_eaten',
            field=models.ManyToManyField(blank=True, related_name='food_eaten', to='product.product'),
        ),
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 23, 2, 54, 263810)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 23, 2, 54, 264808)),
        ),
    ]
