# Generated by Django 4.1.7 on 2023-04-18 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_comment_user_helpful_comment_user_not_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 0, 43, 19, 581602)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 0, 43, 19, 581602)),
        ),
    ]
