# Generated by Django 4.1.7 on 2023-04-18 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_discountbill_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 0, 43, 52, 923451)),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 0, 43, 52, 923451)),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_invite', models.DateTimeField(auto_now_add=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('order_detail', models.ForeignKey(db_column='order_table', on_delete=django.db.models.deletion.CASCADE, to='product.ordertable')),
            ],
            options={
                'db_table': 'invite',
            },
        ),
        migrations.AddField(
            model_name='ordertable',
            name='partner',
            field=models.ManyToManyField(related_name='partner', through='product.Invite', to='product.customer'),
        ),
    ]
