# Generated by Django 4.1.7 on 2023-04-23 11:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_invite_end_time_alter_discountbill_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountbill',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 12, 53, 40, 921808)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 12, 53, 40, 923806)),
        ),
        migrations.AlterField(
            model_name='invite',
            name='time_invite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='intend_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 12, 53, 40, 922807)),
        ),
    ]
