# Generated by Django 4.1.7 on 2023-04-24 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_create_not_signup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator, django.core.validators.MinLengthValidator(16)], verbose_name='email address'),
        ),
    ]
